### ISSUE TITLE
Time Update

### ISSUE THREAD

**Issue by EternaI** [Thor77/TeamspeakStats#1]
I tried the tool but the results on the output .html doesnt refresh, even after deleting it and starting the tsstats again the page show the same times and online users again

**Comment by Thor77** [comment]
Did your log-file change between these two executions?
The onlinetime should change anyway, though. Please enable debug mode (either set `debug = True` in your config or append `-d` to your cli-arguments) and check the debug-log for omitted lines.

**Comment by Thor77** [comment]
Fixed. Please update your installation via pip: `pip install --upgrade tsstats`.
