### ISSUE TITLE
Add supported versions of python to the readme

### ISSUE THREAD

**Issue by djmattyg007** [Thor77/TeamspeakStats#10]
FWIW, I've tested it on python3.5 and it works just fine.

**Comment by djmattyg007** [comment]
Also, thanks for such a beautifully simple fantastic piece of software! I can't wait to set this up for my personal teamspeak server.

**Comment by Thor77** [comment]
> FWIW, I've tested it on python3.5 and it works just fine.

Yeah, tests are sucessfully running for [Python 2.7 and 3.6](https://github.com/Thor77/TeamspeakStats/blob/master/.travis.yml#L3-L4).
Do you really think it's neccessary to add that fact to the README? I guess most users will just assume it will work once they installed it, which should be the case if they're not using a very ancient version.

> Also, thanks for such a beautifully simple fantastic piece of software! I can't wait to set this up for my personal teamspeak server.

Thanks :) Also thank **you** for your great contributions and suggestions!

**Comment by djmattyg007** [comment]
Given Ubuntu 16.04 will be stuck on python3.5 for another year, it might be good to still support it. Just generally I think it's a good idea, for the same reason that you've declared the minimum required version of jinja2 in the requirements.txt file. It also helps contributors know which versions they have to support when submitting patches ;)

**Comment by Thor77** [comment]
>  It also helps contributors know which versions they have to support when submitting patches ;)
They will feel it once they open a PR and Travis-tests are failing for one version :P
No, just kidding. Will add that to the README.md inside the Contribution-section.
