### ISSUE TITLE
Write debug log to stdout

### ISSUE THREAD

**Issue by djmattyg007** [Thor77/TeamspeakStats#15]
Currently if you want to view the debug logging that is turned on when pass the `--debug` flag, you have to modify the code. There should be a way to have this logging output to the terminal.

**Comment by Thor77** [comment]
Currently the debug log is written to  [`debug.txt`](https://github.com/Thor77/TeamspeakStats/blob/master/tsstats/__init__.py#L8) at the current working directory.
What do you mean by "*you have to modify the code*"?
But yeah, an option to print the debug log directly to `stdout` is a good idea.

**Comment by djmattyg007** [comment]
I have to admit I missed `debug.txt`. I modified the code to have it print the debug logging to stdout.

**Comment by Thor77** [comment]
Huh, yeah it's not really obvious from the documentation.
I will add a cli-switch/config-directive to write logs to `stdout` shortly.
