### ISSUE TITLE
Unrecognized Arguments

### ISSUE THREAD

**Issue by Naspyy** [Thor77/TeamspeakStats#21]
```
root@vps:/opt/teamspeak# tsstats -l /opt/teamspeak/logs/ts3server*.log -o /var/www/tsstats.htmlcd
usage: tsstats [-h] [-c CONFIG] [--idmap IDMAP] [-l LOG] [-o OUTPUT] [-d]
               [-ds] [-nod] [-t TEMPLATE] [-dtf DATETIMEFORMAT]
               [-otth ONLINETIMETHRESHOLD]
tsstats: error: unrecognized arguments: /opt/teamspeak/logs/ts3server_2017-04-21__21_08_18.339291_1.log /opt/teamspeak/logs/ts3server_2017-04-21__21_08_35.515297_0.log /opt/teamspeak/logs/ts3server_2017-04-21__21_08_35.515297_1.log
```

**Comment by Thor77** [comment]
Either quote the path-parameter as your shell is expanding it and ``tsstats`` can't handle that:

``tsstats -l "/opt/teamspeak/logs/ts3server*.log" -o /var/www/tsstats.html``

or just give the path of your log-directory to ``-l/--log``:

``tsstats -l /opt/teamspeak/logs/ -o /var/www/tsstats.html``

**Comment by Thor77** [comment]
@Naspyy does your issue persist? If not, please close this issue.

If there's no reaction by Monday, I will close this issue.
