### ISSUE TITLE
Insane Online times

### ISSUE THREAD

**Issue by UnR34L** [Thor77/TeamspeakStats#4]
https://unr34l.co.uk/stats/

Logs are from 2016-04-25 to 2016-10-31

The first seven names have impossible online times (2000+ days in 6 months).

I can provide the logs if you'd like to investigate but ask that you don't share them, to protect the privacy of users.

**Comment by Thor77** [comment]
Thanks for your report!
To debug this issue, I need the affected logs (you can send them to me privately via mail (you can find my mail-address on my GitHub-profile and my gpg-publickey and fingerprint on my website)).
Feel free to anonymize them by replacing nicks, client/server/servergroup/channelgroup/channel-ids and client-uuids with random data.
But please make sure to replace all occurences of an id/uuid with the same replacement as that would affect the stats if you do not.

**Comment by Thor77** [comment]
Uh, I can reproduce this issue with data from my own teamspeak-server (just when parsing multiple files, though so I guess there's a bug in my sort-function).
So I don't really need your logs but would appreciate help with testing a fix once I come up with one.

**Comment by UnR34L** [comment]
No problem, when you find a fix I'll update and report back.

**Comment by Thor77** [comment]
Should be fixed now. Not the best solution, though, because it will cause weird problems for logs without proper filenames (without timestamps).

**Comment by UnR34L** [comment]
Online times now look correct =D

appreciate this, everyone that comes on this teamspeak love the stats, thanks.
